const { chromium } = require('playwright-core');
const path = require('path');
(async () => {
  const exe = '/home/robertsong/.cache/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-linux64/chrome-headless-shell';
  const browser = await chromium.launch({ executablePath: exe, args: ['--no-sandbox'] });
  const url = 'file://' + path.resolve('.', 'xuegu-bian.html');
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  await page.goto(url);
  await page.addStyleTag({ content: 'html{scroll-behavior:auto!important} *{animation:none!important;transition:none!important}' });
  await page.waitForTimeout(300);
  await page.screenshot({ path: 'shot_xg_1_hero_closed.png' });
  await page.click('#hit');
  await page.waitForTimeout(300);
  await page.click('#hit');
  await page.waitForTimeout(300);
  await page.click('#hit');
  await page.waitForTimeout(900);
  await page.screenshot({ path: 'shot_xg_2_hero_open.png' });
  await page.evaluate(() => { document.querySelector('#notes').scrollIntoView(); });
  await page.screenshot({ path: 'shot_xg_3_notes.png' });
  await page.evaluate(() => { document.querySelector('#rail').scrollIntoView(); });
  await page.screenshot({ path: 'shot_xg_4_rail.png' });
  await page.evaluate(() => { document.querySelector('#wallgrid').scrollIntoView({ block: 'start' }); });
  await page.screenshot({ path: 'shot_xg_5_wall.png' });
  await page.click('.cell:nth-child(19)');
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'shot_xg_6_overlay.png' });
  await page.click('#ov-next');
  await page.waitForTimeout(200);
  await page.screenshot({ path: 'shot_xg_7_overlay_next.png' });
  await page.click('#ovx');
  await page.evaluate(() => { document.querySelector('#laws').scrollIntoView(); });
  await page.screenshot({ path: 'shot_xg_8_laws_b.png' });
  await page.evaluate(() => { document.querySelector('[data-law="z"]').click(); });
  await page.waitForTimeout(200);
  await page.screenshot({ path: 'shot_xg_9_laws_z.png' });
  await page.evaluate(() => { document.querySelector('#shelf').scrollIntoView(); });
  await page.screenshot({ path: 'shot_xg_10_shelf.png' });
  await page.evaluate(() => { document.querySelector('#workshop').scrollIntoView(); });
  await page.evaluate(() => { document.querySelector('[data-m="4"]').click(); });
  await page.screenshot({ path: 'shot_xg_11_workshop.png' });
  await page.evaluate(() => { document.querySelector('.coda').scrollIntoView({ block: 'center' }); });
  await page.screenshot({ path: 'shot_xg_12_coda.png' });
  // mobile
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.waitForTimeout(300);
  await page.screenshot({ path: 'shot_xg_13_mob_hero.png' });
  await page.evaluate(() => { document.querySelector('#wallgrid').scrollIntoView(); });
  await page.screenshot({ path: 'shot_xg_14_mob_wall.png' });
  await page.evaluate(() => { document.querySelector('.coda').scrollIntoView({ block: 'center' }); });
  await page.screenshot({ path: 'shot_xg_15_mob_coda.png' });
  await browser.close();
  console.log('done');
})();
