const { chromium } = require('playwright-core');
const path = require('path');
(async () => {
  const exe = '/home/robertsong/.cache/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-linux64/chrome-headless-shell';
  const browser = await chromium.launch({ executablePath: exe, args: ['--no-sandbox'] });
  const url = 'file://' + path.resolve('.', 'sanguo-yanyi.html');
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  await page.goto(url);
  await page.addStyleTag({ content: 'html{scroll-behavior:auto!important}' });
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'shot_sg_1_hero_closed.png' });
  await page.click('#ting');
  await page.waitForTimeout(2400);
  await page.screenshot({ path: 'shot_sg_2_hero_wake.png' });
  await page.evaluate(() => { document.querySelector('.mirow').scrollIntoView({ block: 'center' }); });
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'shot_sg_3_mi.png' });
  await page.evaluate(() => { document.querySelector('.sanrow').scrollIntoView({ block: 'center' }); });
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'shot_sg_4_san.png' });
  await page.evaluate(() => {
    const f = document.querySelectorAll('.fold');
    f[1].scrollIntoView({ block: 'center', inline: 'center' });
  });
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'shot_sg_5_folds.png' });
  await page.evaluate(() => { document.querySelector('.jia').scrollIntoView({ block: 'start' }); });
  await page.evaluate(() => { document.querySelectorAll('.jia details')[0].open = true; document.querySelectorAll('.jia details')[9].open = true; });
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'shot_sg_6_jia.png' });
  await page.evaluate(() => document.querySelector('.coda').scrollIntoView());
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'shot_sg_7_coda.png' });
  const mp = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await mp.goto(url);
  await mp.addStyleTag({ content: 'html{scroll-behavior:auto!important}' });
  await mp.click('#ting');
  await mp.waitForTimeout(2200);
  await mp.screenshot({ path: 'shot_sg_m1_hero.png' });
  await mp.evaluate(() => { document.querySelectorAll('.fold')[0].scrollIntoView({ block: 'center' }); });
  await mp.waitForTimeout(400);
  await mp.screenshot({ path: 'shot_sg_m2_folds.png' });
  await mp.evaluate(() => { document.querySelector('.jia').scrollIntoView({ block: 'start' }); document.querySelectorAll('.jia details')[2].open = true; });
  await mp.waitForTimeout(500);
  await mp.screenshot({ path: 'shot_sg_m3_jia.png' });
  await browser.close();
  console.log('done');
})();
