import { chromium } from '/home/robertsong/workspace/claude/likec4-demo/node_modules/playwright/index.mjs';
const b = await chromium.launch();
const pg = await b.newPage({ viewport: { width: 1280, height: 900 } });
await pg.goto('file:///home/robertsong/workspace/claude/daizhige-daodu/xihu-mengxun.html');
await pg.waitForTimeout(600);
await pg.screenshot({ path: 'shot_xh_gate.png' });
await pg.evaluate(() => document.getElementById('gbtn').dispatchEvent(new MouseEvent('click', {bubbles: true})));
await pg.waitForTimeout(1400);
await pg.screenshot({ path: 'shot_xh_hero.png' });
await pg.evaluate(() => document.getElementById('mbtn').dispatchEvent(new MouseEvent('click', {bubbles: true})));
await pg.waitForTimeout(1800);
await pg.screenshot({ path: 'shot_xh_hero_awake.png' });
await pg.evaluate(() => document.getElementById('mbtn').dispatchEvent(new MouseEvent('click', {bubbles: true})));
await pg.waitForTimeout(1200);
await pg.evaluate(() => window.scrollTo(0, document.querySelector('.paper').offsetTop));
await pg.waitForTimeout(600);
await pg.screenshot({ path: 'shot_xh_paper.png' });
await pg.evaluate(() => window.scrollTo(0, document.querySelector('.sanhu').offsetTop));
await pg.waitForTimeout(500);
await pg.screenshot({ path: 'shot_xh_sanhu.png' });
await pg.evaluate(() => window.scrollTo(0, document.querySelector('.zhou').offsetTop));
await pg.waitForTimeout(500);
await pg.screenshot({ path: 'shot_xh_zhou.png' });
await pg.evaluate(() => document.querySelector('[data-j="jd3"]').dispatchEvent(new MouseEvent('click', {bubbles: true})));
await pg.waitForTimeout(400);
await pg.evaluate(() => document.getElementById('jd3').scrollIntoView({block:'center'}));
await pg.waitForTimeout(400);
await pg.screenshot({ path: 'shot_xh_jd.png' });
await pg.evaluate(() => document.querySelector('.snow').scrollIntoView());
await pg.waitForTimeout(800);
await pg.screenshot({ path: 'shot_xh_snow.png' });
await pg.evaluate(() => document.querySelector('.cts button').dispatchEvent(new MouseEvent('click', {bubbles: true})));
await pg.waitForTimeout(900);
await pg.screenshot({ path: 'shot_xh_snow_lit.png' });
await pg.evaluate(() => document.querySelector('.graves').scrollIntoView());
await pg.waitForTimeout(500);
await pg.screenshot({ path: 'shot_xh_graves.png' });
await pg.evaluate(() => document.querySelector('.coda').scrollIntoView({block:'center'}));
await pg.waitForTimeout(500);
await pg.screenshot({ path: 'shot_xh_coda.png' });

const mob = await b.newPage({ viewport: { width: 390, height: 844 } });
await mob.goto('file:///home/robertsong/workspace/claude/daizhige-daodu/xihu-mengxun.html');
await mob.waitForTimeout(500);
await mob.evaluate(() => document.getElementById('gbtn').dispatchEvent(new MouseEvent('click', {bubbles: true})));
await mob.waitForTimeout(1300);
await mob.screenshot({ path: 'shot_xh_mob_hero.png' });
await mob.evaluate(() => window.scrollTo(0, document.querySelector('.paper').offsetTop));
await mob.waitForTimeout(500);
await mob.screenshot({ path: 'shot_xh_mob_paper.png' });
await mob.evaluate(() => window.scrollTo(0, document.querySelector('.sanhu').offsetTop));
await mob.waitForTimeout(500);
await mob.screenshot({ path: 'shot_xh_mob_sanhu.png' });
await mob.evaluate(() => document.querySelector('.cts button').dispatchEvent(new MouseEvent('click', {bubbles: true})));
await mob.evaluate(() => document.querySelector('.snow').scrollIntoView());
await mob.waitForTimeout(800);
await mob.screenshot({ path: 'shot_xh_mob_snow.png' });
console.log('done');
await b.close();
