const { chromium } = require('playwright-core');
const path = require('path');
(async () => {
  const exe = '/home/robertsong/.cache/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-linux64/chrome-headless-shell';
  const browser = await chromium.launch({ executablePath: exe, args: ['--no-sandbox'] });
  const url = 'file://' + path.resolve('.', 'zhupu-xianglu.html');

  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  await page.goto(url);
  await page.addStyleTag({ content: 'html{scroll-behavior:auto!important} *{animation:none!important;transition:none!important}' });
  await page.waitForTimeout(300);
  await page.screenshot({ path: 's_zp_1_hero_closed.png' });
  await page.click('#hit');
  await page.waitForTimeout(3200);
  await page.screenshot({ path: 's_zp_2_hero_bloom.png' });
  await page.evaluate(() => { document.querySelector('#pingsheng').scrollIntoView(); });
  await page.waitForTimeout(200);
  await page.screenshot({ path: 's_zp_3_xu.png' });
  await page.evaluate(() => { document.querySelector('#zhenji').scrollIntoView(); });
  await page.waitForTimeout(200);
  await page.screenshot({ path: 's_zp_4_shelves.png' });
  await page.waitForTimeout(400);
  await page.screenshot({ path: 's_zp_5_panel_yushen.png' });
  await page.evaluate(() => { document.querySelector('#chengzhu').scrollIntoView(); });
  await page.waitForTimeout(200);
  await page.screenshot({ path: 's_zp_6_rank.png' });
  await page.evaluate(() => { document.querySelector('#shibing').scrollIntoView(); });
  await page.waitForTimeout(200);
  await page.click('#hit');
  await page.waitForTimeout(300);
  await page.screenshot({ path: 's_zp_7_case_flip.png' });
  await page.evaluate(() => { document.querySelector('#zhutai').scrollIntoView(); });
  await page.waitForTimeout(200);
  await page.screenshot({ path: 's_zp_8_tu.png' });
  await page.waitForTimeout(300);
  await page.screenshot({ path: 's_zp_9_winter.png' });
  await page.evaluate(() => { document.querySelector('#liupin').scrollIntoView(); });
  await page.waitForTimeout(200);
  await page.screenshot({ path: 's_zp_10_lanzi.png' });
  await page.evaluate(() => { document.querySelector('.coda').scrollIntoView(); });
  await page.waitForTimeout(200);
  await page.screenshot({ path: 's_zp_11_coda.png' });
  await page.evaluate(() => { document.querySelector('footer').scrollIntoView(); });
  await page.waitForTimeout(200);
  await page.screenshot({ path: 's_zp_12_footer.png' });

  const m = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await m.goto(url);
  await m.addStyleTag({ content: 'html{scroll-behavior:auto!important} *{animation:none!important;transition:none!important}' });
  await m.waitForTimeout(300);
  await m.click('#hit');
  await m.waitForTimeout(3200);
  await m.screenshot({ path: 's_zp_m1_hero.png' });
  await m.evaluate(() => { document.querySelector('#zhenji').scrollIntoView(); });
  await m.waitForTimeout(200);
  await m.screenshot({ path: 's_zp_m2_shelves.png' });
  await m.waitForTimeout(400);
  await m.screenshot({ path: 's_zp_m3_panel.png' });
  await m.evaluate(() => { document.querySelector('#chengzhu').scrollIntoView(); });
  await m.waitForTimeout(200);
  await m.screenshot({ path: 's_zp_m4_rank.png' });
  await m.evaluate(() => { document.querySelector('.coda').scrollIntoView(); });
  await m.waitForTimeout(200);
  await m.screenshot({ path: 's_zp_m5_coda.png' });

  await browser.close();
  console.log('shots done');
})();
