import pkg from '/home/robertsong/workspace/claude/likec4-demo/node_modules/playwright-core/index.js'; const { chromium } = pkg;
const b = await chromium.launch({ executablePath:'/home/robertsong/.cache/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-linux64/chrome-headless-shell', args:['--no-sandbox'] });
const errors=[];
const pg = await b.newPage({ viewport:{width:1280,height:900} });
pg.on('pageerror',e=>errors.push('PAGEERROR: '+e.message));
pg.on('console',m=>{ if(m.type()==='error') errors.push('CONSOLE: '+m.text()); });
await pg.goto('file:///home/robertsong/workspace/claude/daizhige-daodu/jinjing-lu.html');
await pg.waitForTimeout(600);
await pg.screenshot({path:'/tmp/jj_0_hero.png'});
await pg.click('#shangse');
await pg.waitForTimeout(2300);
await pg.screenshot({path:'/tmp/jj_1_hero_colored.png'});
await pg.$eval('#mz',el=>el.scrollIntoView());
await pg.waitForTimeout(900);
await pg.screenshot({path:'/tmp/jj_2_mz.png'});
await pg.$eval('#yy',el=>el.scrollIntoView());
await pg.waitForTimeout(900);
await pg.screenshot({path:'/tmp/jj_3_yy.png'});
await pg.$eval('#sq',el=>el.scrollIntoView());
await pg.waitForTimeout(900);
await pg.screenshot({path:'/tmp/jj_4_wall.png'});
await pg.click('#wall .plate[data-i="12"]');
await pg.waitForTimeout(1400);
await pg.$eval('#detail',el=>el.scrollIntoView({block:'center'}));
await pg.waitForTimeout(500);
await pg.screenshot({path:'/tmp/jj_5_detail12.png'});
await pg.click('#wall .plate[data-i="9"]');
await pg.waitForTimeout(1400);
await pg.screenshot({path:'/tmp/jj_6_detail9.png'});
await pg.$eval('#cw',el=>el.scrollIntoView());
await pg.waitForTimeout(900);
await pg.screenshot({path:'/tmp/jj_7_cw.png'});
await pg.$eval('#hs',el=>el.scrollIntoView());
await pg.waitForTimeout(900);
await pg.screenshot({path:'/tmp/jj_8_hs.png'});
await pg.$eval('#fin',el=>el.scrollIntoView());
await pg.waitForTimeout(900);
await pg.screenshot({path:'/tmp/jj_9_fin.png'});
// 一键上色
await pg.$eval('#sq',el=>el.scrollIntoView());
await pg.click('#allcolor');
await pg.waitForTimeout(2600);
await pg.screenshot({path:'/tmp/jj_10_allcolored.png'});
// 移动端
const m = await b.newPage({ viewport:{width:390,height:844} });
m.on('pageerror',e=>errors.push('M-PAGEERROR: '+e.message));
await m.goto('file:///home/robertsong/workspace/claude/daizhige-daodu/jinjing-lu.html');
await m.waitForTimeout(700);
await m.click('#shangse');
await m.waitForTimeout(2200);
await m.screenshot({path:'/tmp/jj_m0_hero.png'});
await m.$eval('#sq',el=>el.scrollIntoView());
await m.waitForTimeout(800);
await m.click('#wall .plate[data-i="28"]');
await m.waitForTimeout(1300);
await m.$eval('#detail',el=>el.scrollIntoView({block:'center'}));
await m.waitForTimeout(400);
await m.screenshot({path:'/tmp/jj_m1_detail.png'});
await m.$eval('#hs',el=>el.scrollIntoView());
await m.waitForTimeout(800);
await m.screenshot({path:'/tmp/jj_m2_hs.png'});
await m.$eval('#fin',el=>el.scrollIntoView());
await m.waitForTimeout(800);
await m.screenshot({path:'/tmp/jj_m3_fin.png'});
console.log(errors.length?errors.join('\n'):'NO JS ERRORS');
await b.close();
